<?php
  include 'header.php';
?>
<div class="table-responsive-md" style="margin: 5vh 8vw;">
        <table class="table caption-top">
          <caption>List of dear clients:</caption>
          <thead class="table-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Company</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
<?php
  try {
    $query = $db_conn->prepare('select * from client');
    $query->execute();
    $client_data = $query->fetchAll();
    if (!empty($client_data)) {
      foreach($client_data as $c)
      { ?>
            <tr>
              <th scope="row"><?= $c['Id'] ?></th>
              <td scope="row"><?= $c['firstName'] ?></td>
              <td><?= $c['lastName'] ?></td>
              <td><?= $c['companyName'] ?></td>
              <td><?= ($c['status'] == 1 ? "Activated" : "Offline") ?></td>
            </tr>
      <?php
      }
    }
  }
  catch (PDOException $e) {

  }
?>
          </tbody>
        </table>
      </div>
<?php
  include 'footer.php';
?>