<?php
  $count = 1;
  include 'header.php';
?>
<div class="card gap-1 col-5 mx-auto" style="margin: 10vh 0; box-shadow: 3px 3px 16px 1px #ccc;">
  <h5 class="card-header">Create new account</h5>
  <div class="card-body" style="padding: 2em;">
    <form class="row g-3 needs-validation" method="post">
      <input type="hidden" name="action" value="add_new_employee">
      <div class="col-md-6">
        <label for="validationCustom0<?= $count ?>" class="form-label">First name</label>
        <input name="emp_fName" type="text" class="form-control" id="validationCustom0<?= $count++ ?>" required>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <div class="col-md-6">
        <label for="validationCustom0<?= $count ?>" class="form-label">Last name</label>
        <input name="emp_lName" type="text" class="form-control" id="validationCustom0<?= $count++ ?>" required>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>

      <div class="col-md-12">
        <label for="validationCustom0<?= $count ?>" class="form-label">Email Address:</label>
        <input name="emp_mail" type="text" class="form-control" id="validationCustom0<?= $count++ ?>" required>
        <div class="invalid-feedback">Please enter a valid email address.</div>
      </div>
      
      <div class="col-md-12">
        <label for="validationCustom0<?= $count ?>" class="form-label">Enter your password</label>
        <input name="emp_passwd" type="password" class="form-control" id="validationCustom0<?= $count++ ?>" required>
        <div class="invalid-feedback">Please enter a valid email address.</div>
      </div>

      <div class="col-md-12">
        <label for="validationCustom0<?= $count ?>" class="form-label">Re-enter your password</label>
        <input name="emp_verify_passwd" type="password" class="form-control" id="validationCustom0<?= $count++ ?>" required>
        <div class="invalid-feedback">Please enter a valid email address.</div>
      </div>

      <div class="col-12 mx-auto text-center">
        <button class="btn btn-primary" type="submit" style="margin-top: 2vh; padding: .5em 6em;">Create new account</button>
      </div>
    </form>
  </div>
</div>
<?php
  include 'footer.php';
?>