<?php
  include 'header.php';
?>
<section id="offer">
        <div class="flex-container"> <!-- This div contains the flexbox customization -->
            <div>
                <img src="head.png" alt="Nintendo Switch Career">
            </div>
            <div class="divText">
                <h1><em>Assignment 4 Accounting System etc</em></h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisis leo vel fringilla est ullamcorper eget nulla. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Morbi leo urna molestie at elementum eu facilisis sed. Elementum nibh tellus molestie nunc non. Id ornare arcu odio ut sem nulla pharetra diam. Id aliquet lectus proin nibh nisl condimentum. Aliquet enim tortor at auctor urna. Nec tincidunt praesent semper feugiat nibh sed. Purus faucibus ornare suspendisse sed nisi lacus sed. Amet aliquam id diam maecenas ultricies mi eget mauris. Suspendisse potenti nullam ac tortor vitae purus. Donec massa sapien faucibus et. Quisque egestas diam in arcu cursus euismod quis.<br>
                <br>Amet purus gravida quis blandit turpis cursus in hac. Praesent elementum facilisis leo vel. Pharetra convallis posuere morbi leo urna. Orci a scelerisque purus semper. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Porta non pulvinar neque laoreet suspendisse interdum. Nunc sed velit dignissim sodales ut. Cras sed felis eget velit aliquet sagittis id. Amet porttitor eget dolor morbi non arcu risus quis. Nam at lectus urna duis convallis convallis tellus id interdum. Pellentesque id nibh tortor id aliquet. Eget gravida cum sociis natoque. Lectus sit amet est placerat in egestas erat imperdiet sed. </p>
            </div>
        </div>
    </section>
<?php
  include 'footer.php';
?>
